name: 'Security Visualizer'

inputs:
  grafana_password:
    description: 'Grafana admin password'
    required: true
  prometheus_enabled:
    description: 'Enable Prometheus integration'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Deploy Monitoring
      shell: bash
      run: ./${{ github.action_path }}/scripts/deploy-monitoring.sh ${{ inputs.grafana_password }} ${{ inputs.prometheus_enabled }}
      
    - name: Configure Dashboard
      shell: bash
      run: ./${{ github.action_path }}/scripts/configure-dashboard.sh
