name: 'Cluster Setup'
inputs:
  cluster_name:
    description: 'Cluster name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set permissions
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/*.sh
        ls -la ${{ github.action_path }}/scripts/

    - name: Initialize Cluster
      shell: bash
      run: ${{ github.action_path }}/scripts/setup.sh ${{ inputs.cluster_name }}
