name: Kubescape Security Scan

inputs:
  scan_output:
    description: 'Output file path'
    required: true
  kubescape_version:
    description: 'Kubescape version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Kubescape
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
        echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
        
    - name: Run Cluster Scan
      shell: bash
      run: |
        kubescape scan \
          --enable-host-scan \
          --format json \
          --output ${{ inputs.scan_output }}
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: ${{ inputs.scan_output }}
