name: Security Notification

inputs:
  recipients:
    description: 'Comma-separated email list'
    required: true
    default: "najah.wchem@etudiant-isi.utm.tn,saber.fraj@etudiant-isi.utm.tn"

runs:
  using: "composite"
  steps:
    - name: Prepare Report
      shell: bash
      run: |
        echo "Security Scan Completed" > report.txt
        echo "Critical Findings: $(jq '.summary_details.numberOfCriticalSeverity' cluster-scan-results.json)" >> report.txt
        
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        to: ${{ inputs.recipients }}
        subject: "Security Scan Report"
        body: file://report.txt
