name: Setup Minikube Environment

on:
  workflow_call:

env:
  MINIKUBE_VERSION: ${{ vars.MINIKUBE_VERSION || 'v1.32.0' }}
  MINIKUBE_WAIT_TIMEOUT: ${{ vars.MINIKUBE_WAIT_TIMEOUT || '5m' }}

jobs:
  setup-minikube:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.minikube/cache
            ~/.kubescape
          key: ${{ runner.os }}-k8s-${{ env.MINIKUBE_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Configure system
        run: ./.github/scripts/setup-minikube.sh configure-system

      - name: Install Minikube and dependencies
        run: ./.github/scripts/setup-minikube.sh install-components

      - name: Start Minikube cluster
        run: ./.github/scripts/setup-minikube.sh start-cluster

      - name: Verify cluster status
        run: kubectl cluster-info
