name: 'Security Scanner'
inputs:
  target:
    description: 'Target to scan'
    default: '.'
  output_dir:
    description: 'Output directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set permissions
      shell: bash
      run: |
        chmod -R +x ${{ github.action_path }}/scripts/
        
    - name: Create output dir
      shell: bash
      run: mkdir -p ${{ inputs.output_dir }}

    - name: Run Dependency Check
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        ${{ github.action_path }}/scripts/dependency-check.sh \
          "${{ inputs.target }}" \
          "${{ inputs.output_dir }}"
