name: 'Security Scanner'
inputs:
  target:
    description: 'Target to scan'
    default: '.'
  output_dir:
    description: 'Output directory'
    required: true
runs:
  using: "composite"
  steps:
    - run: mkdir -p ${{ inputs.output_dir }}
      shell: bash

    - run: ${{ github.action_path }}/scripts/dependency-check.sh ${{ inputs.target }} ${{ inputs.output_dir }}
      shell: bash
      name: Dependency Scan
