apiVersion: v1
kind: Secret
metadata:
  name: goatvault
  namespace: default
type: Opaque
data:
  k8sgoatvaultkey: azhzLWdvYXQtY2QyZGEyNzIyNDU5MWRhMmI0OGVmODM4MjZhOGE2YzM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitor-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: system-monitor
  template:
    metadata:
      labels:
        app: system-monitor
    spec:
      # Supprimer hostPID et hostIPC
      # hostPID: true
      # hostIPC: true
      # hostNetwork: true
      volumes:
      # Remplacement de hostPath par un volume temporaire emptyDir
      - name: app-data
        emptyDir: {} # Utiliser un volume temporaire au lieu de hostPath
      securityContext: # Ajout d'un securityContext au niveau du pod
        runAsNonRoot: true # Forcer l'exécution en tant qu'utilisateur non root
        runAsUser: 1000 # Utiliser un UID non privilégié
        runAsGroup: 3000
        fsGroup: 2000 # Définir un groupe pour les fichiers
      containers:
      - name: system-monitor
        image: madhuakula/k8s-goat-system-monitor
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
        securityContext:
          allowPrivilegeEscalation: false # Désactiver l'escalade de privilèges
          privileged: false # Désactiver le mode privilégié
          runAsNonRoot: true # Exécuter en tant qu'utilisateur non root
          runAsUser: 1000 # Utiliser un UID non privilégié
          runAsGroup: 3000  # This value is greater than 999
          fsGroup: 2000
          capabilities:
            drop: # Supprimer toutes les capacités inutiles
              - ALL
        ports:
        - containerPort: 8080
        volumeMounts:
        # Montage du volume temporaire emptyDir
        - name: app-data
          mountPath: /app-data # Changer le point de montage pour utiliser le volume temporaire
        env:
          - name: K8S_GOAT_VAULT_KEY
            valueFrom:
              secretKeyRef:
                name: goatvault
                key: k8sgoatvaultkey
---
apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: system-monitor
