name: Kubernetes Security Scan with Stable Grafana Access

on:
  workflow_dispatch:
  push:
    branches: [main, master]

env:
  CLUSTER_SCAN_OUTPUT: "cluster-scan-results.json"
  GRAFANA_ADMIN_PASSWORD: "Admin@Secure123"
  MINIKUBE_VERSION: "v1.32.0"
  KUBESCAPE_VERSION: "v3.0.10"
  GRAFANA_PORT: "3000"  # Port standard

jobs:
  security-scan:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Configure system (optimized)
        run: |
          # Solution pour les problèmes de dépendances
          sudo apt-get update -qq --fix-missing
          sudo apt-get install -qq -y \
            conntrack \
            socat \
            curl \
            apt-transport-https \
            software-properties-common \
            docker.io \
            jq
          
          # Démarrer Docker
          sudo systemctl enable --now docker

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/${{ env.MINIKUBE_VERSION }}/minikube-linux-amd64
          chmod +x minikube
          sudo install minikube /usr/local/bin/minikube
          minikube version

      - name: Start Minikube with Grafana
        run: |
          minikube start \
            --driver=docker \
            --memory=8192 \
            --cpus=4 \
            --addons=metrics-server \
            --wait=all

          # Installer Grafana proprement
          helm repo add grafana https://grafana.github.io/helm-charts
          helm install grafana grafana/grafana \
            --namespace grafana \
            --create-namespace \
            --set persistence.enabled=true \
            --set adminPassword="${{ env.GRAFANA_ADMIN_PASSWORD }}" \
            --set service.type=NodePort \
            --set service.nodePort=${{ env.GRAFANA_PORT }} \
            --wait

          # Configurer l'accès
          minikube service grafana --url -n grafana | grep -o 'http://[^ ]*' > grafana_url.txt
          echo "GRAFANA_URL=$(cat grafana_url.txt)" >> $GITHUB_ENV

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          kubescape version

      - name: Run security scan
        run: |
          kubescape scan \
            --enable-host-scan \
            --format json \
            --output ${{ env.CLUSTER_SCAN_OUTPUT }} \
            --exclude-namespaces kube-system,grafana

      - name: Expose Grafana access
        run: |
          # Démarrer le port-forward
          nohup kubectl port-forward -n grafana svc/grafana 3000:3000 > /dev/null 2>&1 &
          
          echo "=============================================="
          echo "GRAFANA ACCESS INFORMATION"
          echo "Direct URL: $GRAFANA_URL"
          echo "Local port-forward: http://localhost:3000"
          echo "Username: admin"
          echo "Password: ${{ env.GRAFANA_ADMIN_PASSWORD }}"
          echo "=============================================="
          
          # Garder les logs actifs
          echo "Le service reste actif pendant 30 minutes..."
          sleep 1800

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            ${{ env.CLUSTER_SCAN_OUTPUT }}
          retention-days: 3
