name: Kubescape Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  YAML_SCAN_OUTPUT: "yaml-scan-results.json"
  CLUSTER_SCAN_OUTPUT: "cluster-scan-results.json"
  NOTIFICATION_RECIPIENTS: "najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn"

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          $HOME/.kubescape/bin/kubescape version

      - name: Setup Kubernetes Access
        id: setup-kubeconfig
        run: |
          mkdir -p ~/.kube
          
          # Vérifier si le secret existe
          if [ -z "${{ secrets.KUBECONFIG }}" ]; then
            echo "::warning::No KUBECONFIG secret found - skipping cluster scan"
            echo "kubeconfig_valid=false" >> $GITHUB_ENV
            exit 0
          fi
          
          # Essayer d'abord comme texte brut
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config.tmp
          
          # Vérifier si c'est un YAML valide
          if kubectl config view --kubeconfig ~/.kube/config.tmp --raw &> /dev/null; then
            echo "::info::Valid raw YAML kubeconfig detected"
            mv ~/.kube/config.tmp ~/.kube/config
          else
            echo "::info::Trying base64 decode"
            echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.tmp 2> /dev/null || {
              echo "::error::❌ Invalid kubeconfig - neither valid YAML nor base64"
              echo "kubeconfig_valid=false" >> $GITHUB_ENV
              exit 0
            }
            
            # Valider le kubeconfig décodé
            if kubectl config view --kubeconfig ~/.kube/config.tmp --raw &> /dev/null; then
              mv ~/.kube/config.tmp ~/.kube/config
              echo "::info::✅ Valid base64 encoded kubeconfig"
            else
              echo "::error::❌ Decoded kubeconfig is invalid"
              echo "kubeconfig_valid=false" >> $GITHUB_ENV
              exit 0
            fi
          fi
          
          chmod 600 ~/.kube/config
          echo "kubeconfig_valid=true" >> $GITHUB_ENV
          export KUBECONFIG=~/.kube/config
          echo "CLUSTER_NAME=$(kubectl config current-context)" >> $GITHUB_ENV
          kubectl cluster-info

      - name: Scan Kubernetes Manifests
        id: yaml-scan
        run: |
          kubescape scan *.yaml \
            --format json \
            --output ${{ env.YAML_SCAN_OUTPUT }} \
            || echo "YAML scan completed with exit code $?"
          
          [ -f "${{ env.YAML_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.YAML_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.YAML_SCAN_OUTPUT }}"

      - name: Scan Running Cluster
        if: env.kubeconfig_valid == 'true'
        id: cluster-scan
        run: |
          kubescape scan \
            --kubeconfig ~/.kube/config \
            --format json \
            --output ${{ env.CLUSTER_SCAN_OUTPUT }} \
            || echo "Cluster scan completed with exit code $?"
          
          [ -f "${{ env.CLUSTER_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.CLUSTER_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.CLUSTER_SCAN_OUTPUT }}"

      - name: Prepare Notification Data
        id: prepare-notification
        run: |
          if [ "${{ env.kubeconfig_valid }}" = "true" ]; then
            echo "cluster_status=${{ steps.cluster-scan.outcome }}" >> $GITHUB_ENV
          else
            echo "cluster_status=Not scanned (invalid kubeconfig)" >> $GITHUB_ENV
          fi
          
          echo "::set-output name=report_content::Security Scan Results:
            - Repository: ${{ github.repository }}
            - Timestamp: $(date)
            - YAML Files: ${{ steps.yaml-scan.outcome }}
            - Cluster: ${{ env.cluster_status }}
            - Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}
          retention-days: 3

      - name: Send Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          secure: true
          subject: "Kubescape Report - ${{ github.repository }}"
          body: "${{ steps.prepare-notification.outputs.report_content }}"
          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ env.NOTIFICATION_RECIPIENTS }}
          attachments: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Cleanup
        if: always()
        run: |
          [ -f ~/.kube/config ] && rm -f ~/.kube/config
          [ -f ~/.kube/config.tmp ] && rm -f ~/.kube/config.tmp
