name: Kubescape Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  YAML_SCAN_OUTPUT: "yaml-scan-results.json"
  CLUSTER_SCAN_OUTPUT: "cluster-scan-results.json"
  NOTIFICATION_RECIPIENTS: "najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn"

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          $HOME/.kubescape/bin/kubescape version

      - name: Setup Kubernetes Access
        id: setup-cluster
        run: |
          mkdir -p ~/.kube
          
          # Essai de décodage base64 seulement si nécessaire
          if echo "${{ secrets.KUBECONFIG }}" | grep -qE '^[A-Za-z0-9+/]+={0,2}$'; then
            echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config || {
              echo "::warning::Failed to decode as base64, trying raw format"
              echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
            }
          else
            echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          fi
          
          chmod 600 ~/.kube/config
          
          # Vérification améliorée du kubeconfig
          if ! kubectl config view --raw >/dev/null 2>&1; then
            echo "::error::Invalid kubeconfig format. Please check your secret."
            echo "::group::Kubeconfig Content"
            cat ~/.kube/config
            echo "::endgroup::"
            exit 1
          fi
          
          export KUBECONFIG=~/.kube/config
          echo "CLUSTER_NAME=$(kubectl config current-context)" >> $GITHUB_ENV
          kubectl cluster-info

      - name: Scan Kubernetes Manifests
        id: yaml-scan
        run: |
          kubescape scan *.yaml \
            --format json \
            --output ${{ env.YAML_SCAN_OUTPUT }} \
            || echo "YAML scan completed with exit code $?"
          
          [ -f "${{ env.YAML_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.YAML_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.YAML_SCAN_OUTPUT }}"

      - name: Scan Running Cluster
        id: cluster-scan
        run: |
          export KUBECONFIG=~/.kube/config
          kubescape scan \
            --kubeconfig ~/.kube/config \
            --format json \
            --output ${{ env.CLUSTER_SCAN_OUTPUT }} \
            || echo "Cluster scan completed with exit code $?"
          
          [ -f "${{ env.CLUSTER_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.CLUSTER_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.CLUSTER_SCAN_OUTPUT }}"

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Send Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          secure: true
          subject: "Kubescape Report - ${{ env.CLUSTER_NAME || 'No Cluster' }} - ${{ github.repository }}"
          body: |
            Security Scan Results:
            
            - YAML Files: ${{ steps.yaml-scan.outcome }}
            - Cluster: ${{ steps.cluster-scan.outcome if steps.cluster-scan else 'Not scanned' }}
            
            Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ env.NOTIFICATION_RECIPIENTS }}
          attachments: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Cleanup
        if: always()
        run: |
          if [ -f ~/.kube/config ]; then
            shred -u ~/.kube/config || rm -f ~/.kube/config
          fi
