name: Kubescape Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Most reliable method using official installation script
      - name: Install Kubescape
        run: |
          # Install using official method
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          
          # Verify installation
          echo "Installed Kubescape version:"
          $HOME/.kubescape/bin/kubescape version
          
          # Add to PATH for current job
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH

      # Run scan with explicit path
      - name: Run Kubescape scan
        run: |
          $HOME/.kubescape/bin/kubescape scan *.yaml --format json --output results.json || echo "Scan completed with exit code $?"
          [ -f results.json ] && jq '.' results.json || echo "No results file generated"

      # Alternative Docker method (commented out)
      # - name: Run via Docker (fallback)
      #   if: failure()
      #   run: |
      #     docker run --rm -v $(pwd):/data kubescape/kubescape scan /data/*.yaml --format json --output /data/results.json

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Kubescape Report - ${{ github.repository }}"
          body: |
            Kubescape security scan completed.
            
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Scan results attached.
          to: najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: true
          attachments: results.json
