name: Kubescape Minikube Scan

on:
  workflow_dispatch:
  push:
    branches: [main, master]

env:
  MINIKUBE_WAIT_TIMEOUT: "5m"  # Augmentation du timeout

jobs:
  scan-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y conntrack socat

      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          
          # Démarrer Minikube avec des paramètres explicites
          minikube start \
            --driver=docker \
            --force \
            --wait=all \
            --timeout=${{ env.MINIKUBE_WAIT_TIMEOUT }} \
            --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
          
          minikube status
          minikube kubectl -- get nodes

      - name: Configure kubectl access
        run: |
          mkdir -p ~/.kube
          minikube kubectl -- config view --flatten > ~/.kube/config
          
          # Vérification de la connexion avec timeout
          timeout 60 kubectl cluster-info || \
            (echo "::error::Failed to connect to cluster"; exit 1)
          
          kubectl config current-context
          kubectl get ns

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          $HOME/.kubescape/bin/kubescape version

      - name: Scan Minikube Cluster
        timeout-minutes: 10  # Timeout généreux pour le scan
        run: |
          export KUBECONFIG=~/.kube/config
          $HOME/.kubescape/bin/kubescape scan \
            --submit \
            --enable-host-scan \
            --format json \
            --output cluster-scan-results.json \
            --verbose
          
          # Vérification des résultats
          [ -f cluster-scan-results.json ] && \
            jq '.summaryDetails' cluster-scan-results.json || \
            echo "::warning::No scan results file generated"

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-results
          path: |
            cluster-scan-results.json
            ~/.kube/config

      - name: Cleanup
        if: always()
        run: |
          minikube delete
          rm -rf ~/.kube ~/.minikube
