name: Kubescape Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  YAML_SCAN_OUTPUT: "yaml-scan-results.json"
  CLUSTER_SCAN_OUTPUT: "cluster-scan-results.json"
  NOTIFICATION_RECIPIENTS: "najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn"
  KUBECONFIG_TIMEOUT: "10"  # Timeout en secondes pour la connexion au cluster

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          $HOME/.kubescape/bin/kubescape version

      - name: Setup Kubernetes Access
        id: setup-kubeconfig
        run: |
          mkdir -p ~/.kube
          
          # Vérification du secret
          if [ -z "${{ secrets.KUBECONFIG }}" ]; then
            echo "::warning::No KUBECONFIG secret found"
            echo "cluster_available=false" >> $GITHUB_ENV
            exit 0
          fi
          
          # Écriture du kubeconfig
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          
          # Validation basique du format
          if ! kubectl config view --raw &> /dev/null; then
            echo "::error::Invalid kubeconfig format"
            echo "cluster_available=false" >> $GITHUB_ENV
            exit 0
          fi
          
          # Test de connexion avec timeout
          echo "Testing cluster connection with ${{ env.KUBECONFIG_TIMEOUT }}s timeout..."
          export KUBECONFIG=~/.kube/config
          if timeout ${{ env.KUBECONFIG_TIMEOUT }} kubectl cluster-info &> /dev/null; then
            echo "::info::✅ Successfully connected to cluster"
            echo "CLUSTER_NAME=$(kubectl config current-context)" >> $GITHUB_ENV
            echo "cluster_available=true" >> $GITHUB_ENV
          else
            echo "::warning::⚠️ Could not connect to cluster (timeout after ${{ env.KUBECONFIG_TIMEOUT }}s)"
            echo "cluster_available=false" >> $GITHUB_ENV
          fi

      - name: Scan Kubernetes Manifests
        id: yaml-scan
        run: |
          kubescape scan *.yaml \
            --format json \
            --output ${{ env.YAML_SCAN_OUTPUT }} \
            || echo "YAML scan completed with exit code $?"
          
          [ -f "${{ env.YAML_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.YAML_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.YAML_SCAN_OUTPUT }}"

      - name: Scan Running Cluster
        if: env.cluster_available == 'true'
        id: cluster-scan
        timeout-minutes: 5  # Timeout pour le scan complet
        run: |
          export KUBECONFIG=~/.kube/config
          kubescape scan \
            --kubeconfig ~/.kube/config \
            --format json \
            --output ${{ env.CLUSTER_SCAN_OUTPUT }} \
            || echo "Cluster scan completed with exit code $?"
          
          [ -f "${{ env.CLUSTER_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.CLUSTER_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.CLUSTER_SCAN_OUTPUT }}"

      - name: Prepare Report
        id: prepare-report
        run: |
          if [ "${{ env.cluster_available }}" = "true" ]; then
            echo "cluster_status=${{ steps.cluster-scan.outcome }}" >> $GITHUB_ENV
          else
            echo "cluster_status=Cluster unavailable (connection timeout)" >> $GITHUB_ENV
          fi
          
          echo "REPORT_CONTENT=Security Scan Report
          - Repository: ${{ github.repository }}
          - Timestamp: $(date)
          - YAML Scan: ${{ steps.yaml-scan.outcome }}
          - Cluster Status: ${{ env.cluster_status }}
          - Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Send Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          secure: true
          subject: "Kubescape Report - ${{ github.repository }}"
          body: "${{ env.REPORT_CONTENT }}"
          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ env.NOTIFICATION_RECIPIENTS }}
          attachments: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Cleanup
        if: always()
        run: |
          [ -f ~/.kube/config ] && rm -f ~/.kube/config
