name: Kubescape Minikube Scan

on:
  workflow_dispatch:
  push:
    branches: [main, master]

env:
  MINIKUBE_WAIT_TIMEOUT: "300"  # 5 minutes en secondes

jobs:
  scan-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y conntrack socat

      - name: Start Minikube (corrected)
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          
          # Version corrigée sans --timeout flag
          minikube start \
            --driver=docker \
            --force \
            --wait=all \
            --wait-timeout=${{ env.MINIKUBE_WAIT_TIMEOUT }} \
            --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
          
          minikube status
          minikube kubectl -- get nodes

      - name: Configure kubectl access
        run: |
          mkdir -p ~/.kube
          minikube kubectl -- config view --flatten > ~/.kube/config
          kubectl cluster-info
          kubectl config current-context

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          $HOME/.kubescape/bin/kubescape version

      - name: Scan Minikube Cluster
        timeout-minutes: 10
        run: |
          export KUBECONFIG=~/.kube/config
          $HOME/.kubescape/bin/kubescape scan \
            --enable-host-scan \
            --format json \
            --output cluster-scan-results.json
          
          [ -f cluster-scan-results.json ] && jq '.' cluster-scan-results.json

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-results
          path: cluster-scan-results.json

      - name: Cleanup
        if: always()
        run: |
          minikube delete || true
          rm -rf ~/.kube ~/.minikube
