name: Kubescape Security Scan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          # Install using official method
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

          # Verify installation
          echo "Installed Kubescape version:"
          $HOME/.kubescape/bin/kubescape version

          # Add to PATH for current job1111
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH

      - name: Run Kubescape scan
        run: |
          $HOME/.kubescape/bin/kubescape scan *.yaml --format json --output results.json || echo "Scan completed with exit code $?"
          [ -f results.json ] && jq '.' results.json || echo "No results file generated"

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465  # Recommandé pour Gmail
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}  # Utilisez un mot de passe d'application
          secure: true     # Doit être false pour le port 587
          ignore_cert: true
          subject: "Kubescape Report - ${{ github.repository }}"
          body: |
            Kubescape security scan completed.
            
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Scan results attached.
          from: ${{ secrets.GMAIL_USERNAME }}
          to: najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn
          attachments: results.json"
