name: Kubescape Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  YAML_SCAN_OUTPUT: "yaml-scan-results.json"
  CLUSTER_SCAN_OUTPUT: "cluster-scan-results.json"
  NOTIFICATION_RECIPIENTS: "najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn"
  KUBECONFIG_PATH: "${{ github.workspace }}/kubeconfig"

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          curl -LO https://github.com/kubescape/kubescape/releases/latest/download/kubescape-ubuntu-latest
          chmod +x kubescape-ubuntu-latest
          mkdir -p $HOME/.kubescape/bin
          mv kubescape-ubuntu-latest $HOME/.kubescape/bin/kubescape
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          kubescape version

      - name: Setup Kubernetes Access
        id: setup-cluster
        run: |
          if [ -n "${{ secrets.KUBECONFIG }}" ]; then
            mkdir -p $(dirname "$KUBECONFIG_PATH")
            echo "${{ secrets.KUBECONFIG }}" > "$KUBECONFIG_PATH"
            chmod 600 "$KUBECONFIG_PATH"
            echo "cluster_scanned=true" >> $GITHUB_ENV
          else
            echo "cluster_scanned=false" >> $GITHUB_ENV
          fi

      - name: Scan Kubernetes Manifests
        id: yaml-scan
        run: |
          kubescape scan *.yaml \
            --format json \
            --output "${{ env.YAML_SCAN_OUTPUT }}" \
            || echo "YAML scan completed with exit code $?"
          
          [ -f "${{ env.YAML_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.YAML_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.YAML_SCAN_OUTPUT }}"

      - name: Scan Running Cluster
        if: env.cluster_scanned == 'true'
        id: cluster-scan
        run: |
          kubescape scan \
            --kubeconfig "$KUBECONFIG_PATH" \
            --format json \
            --output "${{ env.CLUSTER_SCAN_OUTPUT }}" \
            || echo "Cluster scan completed with exit code $?"
          
          [ -f "${{ env.CLUSTER_SCAN_OUTPUT }}" ] && \
            jq '.' "${{ env.CLUSTER_SCAN_OUTPUT }}" > temp.json && \
            mv temp.json "${{ env.CLUSTER_SCAN_OUTPUT }}"

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Prepare Notification Body
        id: prepare-notification
        run: |
          if [ "${{ env.cluster_scanned }}" = "true" ]; then
            echo "cluster_status=${{ steps.cluster-scan.outcome }}" >> $GITHUB_ENV
            echo "body_line='- Cluster: ${{ steps.cluster-scan.outcome }}'" >> $GITHUB_ENV
          else
            echo "body_line='- Cluster: Not scanned'" >> $GITHUB_ENV
          fi
          echo "::set-output name=notification_body::Security Scan Results:
            - YAML Files: ${{ steps.yaml-scan.outcome }}
            ${{ env.body_line }}
            
            Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          secure: true
          subject: "Kubescape Report - ${{ github.repository }}"
          body: "${{ steps.prepare-notification.outputs.notification_body }}"
          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ env.NOTIFICATION_RECIPIENTS }}
          attachments: |
            ${{ env.YAML_SCAN_OUTPUT }}
            ${{ env.CLUSTER_SCAN_OUTPUT }}

      - name: Cleanup
        if: always()
        run: |
          [ -f "$KUBECONFIG_PATH" ] && rm -f "$KUBECONFIG_PATH"
