name: Kubescape Security Scan

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          # Install Kubescape
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          
          # Add to PATH for current step
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          
          # Verify installation
          echo "Updated PATH: $PATH"
          which kubescape
          kubescape version

      - name: Run Kubescape scan
        run: |
          # Explicitly use full path to ensure it works
          $HOME/.kubescape/bin/kubescape scan *.yaml --format json --output results.json
          
          # Process results
          if [ -f results.json ]; then
            echo "Scan completed successfully"
            jq '.' results.json
          else
            echo "Error: No results file generated"
            exit 1
          fi

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Kubescape Report - ${{ github.repository }}"
          body: |
            Kubescape security scan results:
            - Repository: ${{ github.repository }}
            - Triggered by: ${{ github.event_name }}
            - Commit: ${{ github.sha }}
            - Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: true
          attachments: results.json
