name: Optimized Kubescape Minikube Scan

on:
  workflow_dispatch:
  push:
    branches: [main, master]

env:
  CLUSTER_SCAN_OUTPUT: "cluster-scan-results.json"
  MINIKUBE_VERSION: "v1.32.0"
  KUBESCAPE_VERSION: "v3.0.10"
  MINIKUBE_WAIT_TIMEOUT: "3m"

jobs:
  scan-minikube:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.minikube/cache
            ~/.kubescape
          key: ${{ runner.os }}-k8s-${{ env.MINIKUBE_VERSION }}-${{ env.KUBESCAPE_VERSION }}

      - name: Configure system (optimized)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y --no-install-recommends conntrack socat curl
          sudo swapoff -a 2>/dev/null || true

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/${{ env.MINIKUBE_VERSION }}/minikube-linux-amd64
          chmod +x minikube
          sudo install minikube /usr/local/bin/minikube
          minikube version

      - name: Start Minikube cluster
        run: |
          minikube start \
            --driver=docker \
            --container-runtime=containerd \
            --kubernetes-version=stable \
            --wait=all \
            --wait-timeout=${{ env.MINIKUBE_WAIT_TIMEOUT }} \
            --memory=4096 \
            --cpus=2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape/bin" >> $GITHUB_PATH
          # Vérification de l'installation
          $HOME/.kubescape/bin/kubescape version

      - name: Wait for PATH update
        run: |
          echo "Updated PATH: $PATH"
          which kubescape || echo "kubescape not found in PATH"

      - name: Run Kubescape scan
        run: |
          # Utilisation du chemin complet pour éviter les problèmes de PATH
          $HOME/.kubescape/bin/kubescape scan \
            --enable-host-scan \
            --format json \
            --output cluster-scan-results.json \
            --exclude-namespaces kube-system,kubernetes-dashboard

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-${{ github.run_id }}
          path: cluster-scan-results.json
          retention-days: 1

      - name: Cleanup
        if: always()
        run: |
          minikube delete --purge
          sudo rm -rf ~/.minikube ~/.kube
