name: Security Scan and Notification

on:
  push:
    branches: [ master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          # Installation de Kubescape
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "/home/runner/.kubescape/bin" >> $GITHUB_PATH
          echo "Updated PATH: $PATH"
          echo "Kubescape path: $(which kubescape)"
          kubescape version
      - name: SaberNajeh
        run: |
          export PATH=$PATH:/home/runner/.kubescape/bin " zednaha path"

      - name: Run Kubescape scan
        run: |
          kubescape scan *.yaml --format json --output results.json || echo "Scan completed with exit code $?"
          [ -f results.json ] && jq '.' results.json || echo "No results file generated"

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Security Scan Report - ${{ github.repository }}"
          body: |
            Security scan completed for repository: ${{ github.repository }}
            Commit: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
            Date: ${{ github.event.head_commit.timestamp }}
          to: najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: true
          attachments: results.json
