name: Kubescape Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Reliable Kubescape installation method
      - name: Install and Run Kubescape
        run: |
          # Download the binary directly
          curl -LO https://github.com/kubescape/kubescape/releases/latest/download/kubescape-linux-ubuntu-latest
          chmod +x kubescape-linux-ubuntu-latest
          sudo mv kubescape-linux-ubuntu-latest /usr/local/bin/kubescape
          
          # Verify installation
          kubescape version
          
          # Run scan with proper error handling
          if ! kubescape scan *.yaml --format json --output results.json; then
            echo "Scan failed, creating empty results file"
            echo '{"error": "Scan failed"}' > results.json
          fi
          
          # Show summary
          jq '.' results.json

      # Email notification with proper authentication
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587  # Using TLS instead of SSL
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}  # Must use app password
          subject: "Kubescape Report - ${{ github.repository }}"
          body: |
            Kubescape security scan completed.
            
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Scan results attached.
          to: najah.wchem@etudiant-isi.utm.tn, saber.fraj@etudiant-isi.utm.tn
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: false  # Using TLS instead of SSL
          attachments: results.json
