name: 📧 Notification d'Modification

on:
  workflow_call:
    secrets:
      EMAIL_TO:
        required: true
      EMAIL_FROM:
        required: true
      EMAIL_PWD:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r .github/scripts/notification/requirements.txt

      - name: Send email
        env:
          GMAIL_USER: ${{ secrets.EMAIL_FROM }}
          GMAIL_PASSWORD: ${{ secrets.EMAIL_PWD }}
        run: python .github/scripts/notification/send-alert.py "${{ secrets.EMAIL_TO }}"
