name: 📧 Notification d'Modification

on:
  workflow_call:
    secrets:
      EMAIL_TO:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      - name: Rendre les scripts exécutables
        run: chmod +x .github/scripts/**/*.sh
        shell: bash


      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: pip install -r .github/scripts/notification/requirements.txt

      - name: Envoi de notification
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python .github/scripts/notification/send-alert.py "${{ secrets.EMAIL_TO }}"
