name: Send Notification

on:
  workflow_call:

env:
  CLUSTER_SCAN_OUTPUT: ${{ vars.CLUSTER_SCAN_OUTPUT || 'cluster-scan-results.json' }}
  NOTIFICATION_RECIPIENTS: ${{ vars.NOTIFICATION_RECIPIENTS }}

jobs:
  send-notification:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs: run-scan
    steps:
      - name: Download scan results
        uses: actions/download-artifact@v4
        with:
          name: security-scan-${{ github.run_id }}

      - name: Extract critical findings
        id: findings
        run: |
          CRITICAL_FINDINGS=$(jq '.summary_details.numberOfCriticalSeverity' "$CLUSTER_SCAN_OUTPUT" || echo "0")
          echo "CRITICAL_FINDINGS=$CRITICAL_FINDINGS" >> $GITHUB_ENV

      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          secure: true
          subject: "Kubernetes Security Scan Report - ${{ github.repository }}"
          body: |
            Kubernetes security scan completed with results:
            
            - Cluster: Minikube with Kubernetes Goat
            - Critical Findings: ${{ env.CRITICAL_FINDINGS || 'N/A' }}
            - Run ID: ${{ github.run_id }}
            - Workflow: ${{ github.workflow }}
            
            Scan details:
            - Timestamp: $(date -u)
          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ env.NOTIFICATION_RECIPIENTS }}
          attachments: ${{ env.CLUSTER_SCAN_OUTPUT }}