steps:
  - uses: actions/checkout@v4
    with:
      path: 'repo-root'  # Doit correspondre au chemin utilisé

  - name: Setup Cluster
    uses: ./.github/workflows/modules/cluster  # Chemin relatif direct
    with:
      cluster_name: ${{ env.CLUSTER_NAME }}
